version: '3'

services:
  db:
    container_name: db
    build: ./db
    ports:
      - "27017:27017"

  backend:
    container_name: air-quality-api
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - IQAIR_API_KEY=e9eb954c-0e93-4446-a2c8-566c262d7404
      - IQAIR_API_URL=http://api.airvisual.com/v2

      - DB_PORT=27017
      - DB_HOST=db
      - DB_NAME=pollution
